"""Update Database

Revision ID: 7136169152a7
Revises: 5a5391d086a4
Create Date: 2024-02-07 13:50:36.161642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7136169152a7"
down_revision: Union[str, None] = "5a5391d086a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("display_id", sa.String(length=15), nullable=False)
    )
    op.create_foreign_key(
        None,
        "posts",
        "users",
        ["display_id"],
        ["display_id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "display_id")
    # ### end Alembic commands ###
