"""Rename posts table primarykey

Revision ID: 37856d48749b
Revises: 0455358ee6ed
Create Date: 2024-01-14 12:57:27.283046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37856d48749b"
down_revision: Union[str, None] = "0455358ee6ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("postid", sa.Integer(), nullable=False))
    op.drop_column("posts", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.drop_column("posts", "postid")
    # ### end Alembic commands ###
