"""Added date_of_birth, profile columns.

Revision ID: e5d8cd1a0b67
Revises: e22a169b50ba
Create Date: 2024-01-27 16:05:26.747685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5d8cd1a0b67"
down_revision: Union[str, None] = "e22a169b50ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("date_of_birth", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("profile", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_initialized", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_initialized")
    op.drop_column("users", "profile")
    op.drop_column("users", "date_of_birth")
    # ### end Alembic commands ###
