"""Added User to headder columns.

Revision ID: d83f41d73fea
Revises: fabf3fb8cee4
Create Date: 2024-02-02 23:14:46.560745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d83f41d73fea"
down_revision: Union[str, None] = "fabf3fb8cee4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("headder", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "headder")
    # ### end Alembic commands ###
