"""edit following&users table column.

Revision ID: b490e52ddfc2
Revises: c2195699e359
Create Date: 2024-02-20 09:09:36.432275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b490e52ddfc2"
down_revision: Union[str, None] = "c2195699e359"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("following_user_id_fkey", "following", type_="foreignkey")
    op.drop_column("following", "user_id")
    op.add_column("users", sa.Column("followers_count", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("following_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "following_count")
    op.drop_column("users", "followers_count")
    op.add_column(
        "following",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "following_user_id_fkey",
        "following",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
