"""users table fix typo headder to header

Revision ID: 8f2947b7343f
Revises: 53e353cfbc1d
Create Date: 2024-02-04 15:24:43.599451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8f2947b7343f"
down_revision: Union[str, None] = "53e353cfbc1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("header", sa.String(), nullable=True))
    op.drop_column("users", "headder")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("headder", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "header")
    # ### end Alembic commands ###
