"""rename repost, favorite column

Revision ID: 53e353cfbc1d
Revises: 72f275fdc992
Create Date: 2024-02-04 14:13:25.492219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53e353cfbc1d"
down_revision: Union[str, None] = "72f275fdc992"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("favorite_count", sa.Integer(), nullable=True))
    op.add_column("posts", sa.Column("repost_count", sa.Integer(), nullable=True))
    op.drop_column("posts", "favorite")
    op.drop_column("posts", "repost")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("repost", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "posts", sa.Column("favorite", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("posts", "repost_count")
    op.drop_column("posts", "favorite_count")
    # ### end Alembic commands ###
