"""Renamed posts table like colomn

Revision ID: 72f275fdc992
Revises: d83f41d73fea
Create Date: 2024-02-03 16:19:20.505615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "72f275fdc992"
down_revision: Union[str, None] = "d83f41d73fea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("favorite", sa.Integer(), nullable=True))
    op.drop_column("posts", "like")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts", sa.Column("like", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("posts", "favorite")
    # ### end Alembic commands ###
