"""Update Database

Revision ID: 5a5391d086a4
Revises: 65d12023acdd
Create Date: 2024-02-07 13:29:30.662934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5a5391d086a4"
down_revision: Union[str, None] = "65d12023acdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("posts", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "posts", "content", existing_type=sa.VARCHAR(length=500), nullable=False
    )
    op.alter_column(
        "posts", "favorite_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("posts", "repost_count", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("token_code", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "token_code", "seal", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("token_code", "is_used", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "is_initialized", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "is_initialized", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("users", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("token_code", "is_used", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "token_code", "seal", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("token_code", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("posts", "repost_count", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "posts", "favorite_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "posts", "content", existing_type=sa.VARCHAR(length=500), nullable=True
    )
    op.alter_column("posts", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
