version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_fastapi
    container_name: 'fastapi'
    working_dir: '/root/src'
    ports:
      - '8000:8000'
    restart: always
    volumes:
      - ./api:/root/src/api:ro

    tty: true
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: 'postgres-db'
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

volumes:
  postgres_data: